# Generated by Django 5.0.6 on 2024-06-13 13:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declaration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaration',
            name='declaration_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='declaration_no',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='gross_weight',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='measurements',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='net_weight',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='nmbr_of_packages',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='request_no',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('goods_description', models.TextField(max_length=200, null=True)),
                ('static_quantity_unit', models.FloatField(null=True)),
                ('supp_quantity_unit', models.FloatField(null=True)),
                ('unit_weight', models.FloatField(null=True)),
                ('goods_value', models.FloatField(null=True)),
                ('cif_value', models.FloatField(null=True)),
                ('duty_fee', models.FloatField(null=True)),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='declaration.declaration')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
